version: '3'
services:
  web:
    build: ./web
    ports:
     - "3000:3000"
    # volumes:
    #  - .:/code
  db:
    # build: ./dbase
    image: sath89/oracle-12c
    ports:
      # - "8080:8080"
      - "1521:1521"