#
# docker-compose 
# https://docs.docker.com/compose/
# run with `docker-compose up`
#

# extra comments have been added
# for those, like me, who are new to docker

version: '3'    # docker-compose version
services:       # service = container

#
# build our own oracle xe 12c on ubuntu
# basically `docker run -it -p 1521:1521 sath89/oracle-12c /bin/bash /entrypoint.sh`
# from https://github.com/MaksymBilenko/docker-oracle-12c 
# see https://github.com/tgriesser/knex/blob/ece2da12cac2906d7ef88e930937e0d3690982af/scripts/oracle-tests-Dockerfile 
  db:
    image: sath89/oracle-12c
    environment:
      - WEB_CONSOLE=false     # disables enterprise manager
    ports:                    # map ports to access on your laptop
      - "1521:1521"           # Port for tnslistener (database connection)
    entrypoint:
      - bash
      - /entrypoint.sh

# 
# builds our graphql app
# basicaly `docker run -it -p 3000:3000 /bin/bash `
  web:          
    build: ./web
    image: node-oracledb
    depends_on:
      - db
    working_dir: /src
    environment:
      - DB=db             # host will be "db" rather than "localhost"
    ports:                # ^ see https://forums.docker.com/t/localhost-and-docker-compose-networking-issue/23100/2
     - "3000:3000"        # port our graphql server runs on 
